server:
  port: 8761

Spring:
  application:
    name: discovery-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka
#      defaultZone: http://localhost:8762/eureka, http://DOWONui-MacBookPro.local:8763/eureka